spring.application.name=vk-post
vk.access.token=${VK_ACCESS_TOKEN}
server.port=${SERVER_PORT:8081}

spring.web.resources.add-mappings=true

spring.security.headers.csp=script-src 'self'; img-src 'self' data:; object-src 'none'
spring.security.csp.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/childrenrailway
spring.datasource.username=postgres
spring.datasource.password=root
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql



spring.http.multipart.enabled = true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.admin.username=MainTrain
app.admin.password=${ADMIN_PASSWORD}

app.upload.food.dir=./uploads/food-services

app.number-phone=+7 (863) 251-27-04
