spring.application.name=vk-post
vk.access.token=${VK_ACCESS_TOKEN:49d6491b49d6491b49d6491b8e4aec9698449d649d6491b210cd4e323b0476b2d36ccd4}
server.port=${SERVER_PORT:8081}
logging.level.org.springframework=DEBUG
logging.level.by.mcsaltine.vkpost=DEBUG
spring.web.resources.static-locations=classpath:/static/